### 1. buat matrix X dengan ukuran 2x3 menggunakan numpy

In [21]:
import numpy as np

In [22]:
print("Matriks X (Numpy) dengan ukuruan 2x3:")
X = np.array([[69, 42, 2], [1, 6, 7]])
X

Matriks X (Numpy) dengan ukuruan 2x3:


array([[69, 42,  2],
       [ 1,  6,  7]])

- hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum

In [23]:
print("hasil penjumlahan elemen matrix X dengan fungsi sum:")
X.sum()

hasil penjumlahan elemen matrix X dengan fungsi sum:


np.int64(127)

- buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [24]:
import tensorflow as tf

In [25]:
print("Matriks X_tf (TensorFlow) dengan ukuran 2x3:")
X_tf = tf.Variable([[69, 42, 2], [1, 6, 7]])
X_tf

Matriks X_tf (TensorFlow) dengan ukuran 2x3:


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[69, 42,  2],
       [ 1,  6,  7]], dtype=int32)>

### 2. hitung hasil penjumlahan seluruh elemen matrix X

In [26]:
print("hasil penjumlahan seluruh elemen matrix X:")
X.sum()

hasil penjumlahan seluruh elemen matrix X:


np.int64(127)

- hitung hasil penjumlahan seluruh elemen matrix X_pt.

Disini karena tidak ada soal untuk membuat variabel matriks pytorch, maka saya tambahkan dulu

In [27]:
import torch

In [28]:
print("Matriks X_pt (PyTorch) dengan ukuran 2x3: ")
X_pt = torch.tensor([[69, 42, 2], [1, 6, 7]])
X_pt

Matriks X_pt (PyTorch) dengan ukuran 2x3: 


tensor([[69, 42,  2],
        [ 1,  6,  7]])

In [29]:
print("hasil penjumlahan seluruh elemen matrix X_pt:")
X_pt.sum()

hasil penjumlahan seluruh elemen matrix X_pt:


tensor(127)

- hitung hasil penjumlahan seluruh elemen matrix X_tf

In [30]:
print("hasil penjumlahan seluruh elemen matrix X_tf:")
X_tf.numpy().sum()

hasil penjumlahan seluruh elemen matrix X_tf:


np.int64(127)

### 3. hitung hasil penjumlahan matrix X berdasarkan row nya

In [31]:
print("hasil penjumlahan matrix X:")
X.sum(axis=1)

hasil penjumlahan matrix X:


array([113,  14])

- hitung hasil penjumlahan matrix X_pt berdasarkan row nya

In [32]:
print("hasil penjumlahan matrix X_pt:")
torch.sum(X_pt, 1)

hasil penjumlahan matrix X_pt:


tensor([113,  14])

- hitung hasil penjumlahan matrix X_tf berdasarkan row nya

In [33]:
print("hasil penjumlahan matrix X_tf: ")
tf.reduce_sum(X_tf, 1)

hasil penjumlahan matrix X_tf: 


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([113,  14], dtype=int32)>

### 4. hitung hasil penjumlahan matrix X berdasarkan kolom nya

In [34]:
print("hasil penjumlahan matrix X")
X.sum(axis=0)

hasil penjumlahan matrix X


array([70, 48,  9])

- hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya

In [35]:
print("hasil penjumlahan matrix X_pt: ")
torch.sum(X_pt, 0)

hasil penjumlahan matrix X_pt: 


tensor([70, 48,  9])

- hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya

In [36]:
print("hasil penjumlahan matrix X_tf: ")
tf.reduce_sum(X_tf, 0)

hasil penjumlahan matrix X_tf: 


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([70, 48,  9], dtype=int32)>

### 5. hitung nilai minimal dari matrix X, X_pt dan X_tf

In [37]:
print("Nilai minimal dari X:")
X.min()

Nilai minimal dari X:


np.int64(1)

In [38]:
print("Nilai minimal dari X_pt:")
X_pt.min()

Nilai minimal dari X_pt:


tensor(1)

In [39]:
print("Nilai minimal dari X_tf:")
tf.reduce_min(X_tf)

Nilai minimal dari X_tf:


<tf.Tensor: shape=(), dtype=int32, numpy=1>

- hitung nilai maksimal dari matrix X, X_pt dan X_tf

In [40]:
print("Nilai maksimal dari X:")
X.max()

Nilai maksimal dari X:


np.int64(69)

In [41]:
print("Nilai maksimal dari X_pt:")
X_pt.max()

Nilai maksimal dari X_pt:


tensor(69)

In [42]:
print("Nilai maksimal dari X_tf:")
tf.reduce_max(X_tf)

Nilai maksimal dari X_tf:


<tf.Tensor: shape=(), dtype=int32, numpy=69>

- hitung nilai rata-rata dari matrix X, X_pt dan X_tf

In [43]:
print("Nilai rata-rata dari X:")
X.mean()

Nilai rata-rata dari X:


np.float64(21.166666666666668)

In [44]:
print("Nilai rata-rata dari X_pt:")
X_pt.float().mean()

Nilai rata-rata dari X_pt:


tensor(21.1667)

In [45]:
print("Nilai rata-rata dari X_tf):")
tf.reduce_mean(tf.cast(X_tf, tf.float32))

Nilai rata-rata dari X_tf):


<tf.Tensor: shape=(), dtype=float32, numpy=21.16666603088379>

### 6. hitung hasil perkalian seluruh elemen matrix X

In [46]:
print("hasil perkalian seluruh elemen matrix X:")
X.prod()

hasil perkalian seluruh elemen matrix X:


np.int64(243432)

- hitung hasil perkalian seluruh elemen matrix X_pt

In [47]:
print("hasil perkalian seluruh elemen matrix X_pt:")
X_pt.prod()

hasil perkalian seluruh elemen matrix X_pt:


tensor(243432)

- hitung hasil perkalian seluruh elemen matrix X_tf

In [48]:
print("hasil perkalian seluruh elemen matrix X_tf:")
tf.reduce_prod(X_tf)

hasil perkalian seluruh elemen matrix X_tf:


<tf.Tensor: shape=(), dtype=int32, numpy=243432>