Kelompok 1 D, 25. Symmetric and Identity Matrices

In [8]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
import torch
A = torch.tensor ([[5, 7, 2], [7, 6, 9], [2, 9, 4]])
A

tensor([[5, 7, 2],
        [7, 6, 9],
        [2, 9, 4]])

In [9]:
A.T

tensor([[5, 7, 2],
        [7, 6, 9],
        [2, 9, 4]])

In [10]:
A.T==A

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [13]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

import torch
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I


tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [15]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1

b_pt = torch.tensor([[5], [7], [2], [6]])

b_pt


tensor([[5],
        [7],
        [2],
        [6]])

In [16]:
# kalikan matrix I dengan vector b_pt

result = torch.matmul(I, b_pt)
result

tensor([[5],
        [7],
        [2],
        [6]])