Kelompok 1 D,
23. frobenius norm

Numpy

In [13]:
# menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import numpy as np

X_np = np.array([[7, 6, 7], [3, 7, 6], [9, 8, 5]])
X_np


array([[7, 6, 7],
       [3, 7, 6],
       [9, 8, 5]])

In [7]:
(7**2 + 6**2 + 7**2 + 3**2 + 7**2 + 6**2 + 9**2 + 8**2 + 5**2)**(1/2)

19.949937343260004

In [5]:
np.linalg.norm(X_np)

np.float64(19.949937343260004)

Pytorch

In [17]:
import torch

X_pt = torch.tensor([[7, 6, 7], [3, 7, 6], [9, 8, 5]])
X_pt

tensor([[7, 6, 7],
        [3, 7, 6],
        [9, 8, 5]])

In [23]:
torch.norm(X_pt.float())

tensor(19.9499)

Tensorflow

In [26]:
import tensorflow as tf

X_tf = tf.Variable([[7, 6, 7], [3, 7, 6], [9, 8, 5]])
X_tf


<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[7, 6, 7],
       [3, 7, 6],
       [9, 8, 5]], dtype=int32)>

In [28]:
tf.norm(tf.cast(X_tf, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=19.94993782043457>