In [1]:
# Matrix Multiplication

import numpy as np
import torch
import tensorflow as tf

# 1. Buat matrix A ukuran 2x3 dan vector b ukuran 3x1 menggunakan numpy
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1],
              [2],
              [3]])
A
b

array([[1],
       [2],
       [3]])

In [2]:
# Buat matrix A_pt ukuran 2x3 dan vector b_pt ukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])
b_pt = torch.tensor([[1],
                     [2],
                     [3]])
A_pt
b_pt

tensor([[1],
        [2],
        [3]])

In [3]:
# Buat matrix A_tf ukuran 2x3 dan vector b_tf ukuran 3x1 menggunakan tensorflow
A_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])
b_tf = tf.constant([[1],
                    [2],
                    [3]])
A_tf
b_tf

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
# Tampilkan ukuran matrix A dan vector b
print(A.shape)
print(b.shape)

(2, 3)
(3, 1)


In [4]:
# Kalikan matrix A dengan vector b
hasil_Ab = np.matmul(A, b)
hasil_Ab

array([[14],
       [32]])

In [5]:
# Kalikan matrix A_pt dengan vector b_pt
hasil_Ab_pt = torch.matmul(A_pt, b_pt)
hasil_Ab_pt

tensor([[14],
        [32]])

In [ ]:
# Kalikan matrix A_tf dengan vector b_tf
hasil_Ab_tf = tf.matmul(A_tf, b_tf)
hasil_Ab_tf

In [6]:
# Buat matrix B ukuran 3x3 menggunakan numpy
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Buat matrix B_pt ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
# Buat matrix B_tf ukuran 3x3 menggunakan tensorflow
B_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
# Kalikan matrix A dengan matrix B
hasil_AB = np.matmul(A, B)
hasil_AB

array([[30, 36, 42],
       [66, 81, 96]])

In [10]:
# Kalikan matrix A_pt dengan matrix B_pt
hasil_AB_pt = torch.matmul(A_pt, B_pt)
hasil_AB_pt

tensor([[30, 36, 42],
        [66, 81, 96]])

In [11]:
# Kalikan matrix A_tf dengan matrix B_tf
hasil_AB_tf = tf.matmul(A_tf, B_tf)
hasil_AB_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [12]:
# Buktikan apakah perkalian matrix bersifat komutatif? (AB = BA)
print("AB =")
print(np.matmul(A, B))
print("BA tidak bisa dihitung karena ukuran B = 3x3 dan A = 2x3 tidak sesuai.")
print("Jadi, perkalian matrix tidak bersifat komutatif.")

AB =
[[30 36 42]
 [66 81 96]]
BA tidak bisa dihitung karena ukuran B = 3x3 dan A = 2x3 tidak sesuai.
Jadi, perkalian matrix tidak bersifat komutatif.
