### Matrix Multiplication Exercise

In [ ]:
import torch

In [13]:
a = torch.tensor([[12, 22, 23], [24, 25, 26], [32, 31, 30]])
M_q

tensor([[12, 22, 23],
        [24, 25, 26],
        [32, 31, 30]])

In [14]:
b = torch.tensor([[-1, 2, -3], [4, 5, -6]]).T
V_q

tensor([[-1,  4],
        [ 2,  5],
        [-3, -6]])

In [15]:
torch.matmul(M_q, V_q)

tensor([[-37,  20],
        [-52,  65],
        [-60, 103]])