Kelompok 1 D, 25. Symmetric and Identity Matrices

In [4]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
import torch
A = torch.tensor ([[7, 6, 7], [3, 7, 6], [9, 8, 5]])
A

tensor([[7, 6, 7],
        [3, 7, 6],
        [9, 8, 5]])

In [5]:
A.T

tensor([[7, 3, 9],
        [6, 7, 8],
        [7, 6, 5]])

In [6]:
A.T==A

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [10]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

import torch
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I


tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [12]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1

b_pt = torch.tensor([[5], [7], [2], [6]])
b_pt


tensor([[5],
        [7],
        [2],
        [6]])

In [15]:
# kalikan matrix I dengan vector b_pt

result = torch.matmul(I, b_pt)
result

tensor([[5],
        [7],
        [2],
        [6]])